INSERT INTO AUTHOR (ID, FIRSTNAME, LASTNAME) VALUES ( 1, 'Fred', 'Booblik' );
INSERT INTO AUTHOR (ID, FIRSTNAME, LASTNAME) VALUES ( 2, 'SpongeBob', 'SquarePants' );
INSERT INTO GENRE (ID, NAME) VALUES ( 1, 'Comics' );
INSERT INTO BOOK (ID, NAME, AUTHOR_ID, GENRE_ID) VALUES ( 1, 'Battle for Bikini', 1, 1 );
INSERT INTO BOOK (ID, NAME, AUTHOR_ID, GENRE_ID) VALUES ( 2, 'Bikini Bottom', 2, 1 );
