DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR
(
    ID BIGINT AUTO_INCREMENT NOT NULL
        CONSTRAINT PK_AUTHOR PRIMARY KEY ,
    NAME VARCHAR(255),
    SURNAME  VARCHAR(255)
);


DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE
(
    ID BIGINT AUTO_INCREMENT NOT NULL
        CONSTRAINT PK_GENRE PRIMARY KEY,
    NAME VARCHAR(255)
);


DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK
(
    ID BIGINT AUTO_INCREMENT NOT NULL
        CONSTRAINT PK_BOOK PRIMARY KEY,
    NAME VARCHAR(255)
);
ALTER TABLE BOOK
    ADD AUTHOR_ID BIGINT;

ALTER TABLE BOOK
    ADD CONSTRAINT FK_BOOK_AUTHOR_ID
        FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID) ON UPDATE CASCADE ON DELETE SET NULL
;
ALTER TABLE BOOK
    ADD GENRE_ID BIGINT;

ALTER TABLE BOOK
    ADD CONSTRAINT FK_BOOK_GENRE_ID
        FOREIGN KEY (GENRE_ID) REFERENCES GENRE (ID) ON UPDATE CASCADE ON DELETE SET NULL;
