spring:
  data:
    mongodb:
      database: books

mongock:
#  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.hw15.mongock.changelog
