INSERT INTO AUTHOR (NAME, SURNAME) VALUES ( 'Robert Louis', 'Stevenson' );
INSERT INTO AUTHOR (NAME, SURNAME) VALUES ( 'Lewis', 'Carroll' );
INSERT INTO AUTHOR (NAME, SURNAME) VALUES ( 'Daniel', 'Defoe' );
INSERT INTO GENRE (NAME) VALUES ( 'Classic' );
INSERT INTO GENRE (NAME) VALUES ( 'Fantasy' );
INSERT INTO BOOK (NAME, AUTHOR_ID, GENRE_ID) VALUES ( 'Treasure Island', 1, 2 );
INSERT INTO BOOK (NAME, AUTHOR_ID, GENRE_ID) VALUES ( 'Alice in Wonderland', 2, 2 );